# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: qbitorrent
output: ./models.gen.go
generate:
  models: true
output-options:
  skip-prune: true
  nullable-type: false
